- model:
    name: 'Ensemble_mean_0_optimizedModels'
    ensemble_combiner: 'mean'
    ensemble_model_configs:
      - model:
          name_to_load: 'efficientnet_v2_l_400_0.7764'
        test:
          batch_size: 96
      - model:
          name_to_load: 'regnet_y_16gf_400_0.7511'
          weights: 'IMAGENET1K_SWAG_E2E_V1'
        test:
          batch_size: 96
      - model:
          name_to_load: 'efficientnet_v2_m_400_0.7406'
        test:
          batch_size: 96
      - model:
          name_to_load: 'convnext_base_400_0.7506'
        test:
          batch_size: 96
      - model:
          name_to_load: 'resnext101_64x4d_400_0.7376'
        test:
          batch_size: 96
      - model:
          name_to_load: 'convnext_large_400_0.7537'
        test:
          batch_size: 96      
  test:
    batch_size: 96