- model:
    name: 'Ensemble_einsum_0_optimizedModels'
    ensemble_combiner: 'einsum'
    ensemble_model_configs:
      - model:
          name_to_load: 'efficientnet_v2_l_400_0.7764'
        train:
          batch_size: 96
      - model:
          name_to_load: 'regnet_y_16gf_400_0.7511'
          weights: 'IMAGENET1K_SWAG_E2E_V1'
        train:
          batch_size: 96
      - model:
          name_to_load: 'efficientnet_v2_m_400_0.7406'
        train:
          batch_size: 96
      - model:
          name_to_load: 'convnext_base_400_0.7506'
        train:
          batch_size: 96
      - model:
          name_to_load: 'resnext101_64x4d_400_0.7376'
        train:
          batch_size: 96
      - model:
          name_to_load: 'convnext_large_400_0.7537'
        train:
          batch_size: 96      
  train:
    learning_rate: 1.0e-4
    batch_size: 96